[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[workspace]
#members = ["crates/*"]

[workspace.dependencies]

[[bin]]
name = "01"
path = "days/01.rs"

[[bin]]
name = "02"
path = "days/02.rs"
